# Generated by Django 5.0.3 on 2024-10-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0003_client_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='agency_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
