# Generated by Django 4.2.16 on 2024-11-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0004_agency_agency_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/agency_profile_images/'),
        ),
        migrations.AddField(
            model_name='client',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_images/'),
        ),
    ]
