# Generated by Django 4.1.7 on 2024-11-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0005_agency_profile_image_client_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='stripe_agency_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
