# Generated by Django 4.2.16 on 2024-11-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0006_agency_stripe_agency_id_client_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='agency_profile_images/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
