# Generated by Django 4.2.16 on 2024-11-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0008_alter_client_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_identificacion_biometrica_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='id_identificacion_oficial_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
