# Generated by Django 4.2.16 on 2024-11-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0009_client_id_identificacion_biometrica_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
