# Generated by Django 4.2.16 on 2024-11-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0010_agency_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='suburb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='town',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
