# Generated by Django 4.2.16 on 2024-11-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0011_agency_suburb_agency_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='profile_image',
            field=models.ImageField(blank=True, default='img/default_profile.jpg', null=True, upload_to='agency_profile_images/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_image',
            field=models.ImageField(blank=True, default='img/default_profile.jpg', null=True, upload_to='profile_images'),
        ),
    ]
