# Generated by Django 4.2 on 2024-11-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0013_alter_agency_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
