# Generated by Django 4.2 on 2024-11-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0014_alter_client_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default_profile.jpg', null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default_profile.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
