# Generated by Django 4.2 on 2024-11-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0016_alter_agency_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='profile_image',
            field=models.CharField(blank=True, default='img/default_profile.jpg', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_image',
            field=models.CharField(blank=True, default='img/default_profile.jpg', max_length=255, null=True),
        ),
    ]
