# Generated by Django 4.2.16 on 2024-11-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0017_alter_agency_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
