# Generated by Django 4.2.16 on 2024-11-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0018_alter_agency_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='identificator',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
