# Generated by Django 4.2 on 2024-11-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0019_client_identificator'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='codigo_recuperacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='codigo_recuperacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
