# Generated by Django 4.1.7 on 2024-11-22 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0020_agency_codigo_recuperacion_and_more'),
        ('appUser', '0020_agency_cover_photo'),
    ]

    operations = [
    ]
