# Generated by Django 4.2.16 on 2024-11-22 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0021_merge_20241121_1921'),
        ('appUser', '0021_merge_20241121_2109'),
        ('appUser', '0021_merge_20241121_2111'),
    ]

    operations = [
    ]
