# Generated by Django 4.1.7 on 2024-11-22 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0021_merge_20241121_2111'),
        ('appUser', '0021_merge_20241121_2120'),
    ]

    operations = [
    ]
