# Generated by Django 4.2 on 2024-11-22 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0022_merge_20241121_2350'),
        ('appUser', '0022_merge_20241122_0048'),
    ]

    operations = [
    ]
