# Generated by Django 4.2.16 on 2024-11-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0023_merge_20241122_1010'),
        ('appUser', '0024_alter_agency_certificate'),
    ]

    operations = [
    ]
