# Generated by Django 4.2.16 on 2024-11-22 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0023_merge_20241122_0830'),
        ('appUser', '0025_merge_20241122_1220'),
    ]

    operations = [
    ]
