# Generated by Django 4.1.7 on 2024-11-22 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0023_merge_20241122_1240'),
        ('appUser', '0025_merge_20241122_1220'),
    ]

    operations = [
    ]
