# Generated by Django 5.0.3 on 2024-10-14 05:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appTour', '0001_initial'),
        ('appUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('credit_card', 'Tarjeta de Crédito/Débito'), ('paypal', 'PayPal')], max_length=20)),
                ('stripe_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='appUser.agency')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='appUser.client')),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
                'ordering': ['created_at', 'method_type'],
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallado', 'Fallado'), ('cancelado', 'Cancelado'), ('procesando', 'Procesando'), ('autorizado', 'Autorizado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='appUser.agency')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='appUser.client')),
                ('payment_method', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='appPayment.paymentmethod')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='appTour.reservation')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['payment_date'],
            },
        ),
    ]
