# Generated by Django 4.1.7 on 2024-11-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPayment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
