# Generated by Django 4.1.7 on 2024-11-03 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPayment', '0002_payments_payment_intent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='stripe_payment_id',
            new_name='stripe_payment_method_id',
        ),
    ]
