# Generated by Django 4.1.7 on 2024-11-14 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPayment', '0003_rename_stripe_payment_id_paymentmethod_stripe_payment_method_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPayment.paymentmethod'),
        ),
    ]
