# Generated by Django 4.1.7 on 2024-11-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPayment', '0003_rename_stripe_payment_id_paymentmethod_stripe_payment_method_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='card_brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payments',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
