# Generated by Django 4.1.7 on 2024-11-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPayment', '0004_paymentmethod_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='card_brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
