# Generated by Django 4.1.7 on 2024-11-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPayment', '0005_remove_payments_card_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='transfer_number',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
