# Generated by Django 4.1.7 on 2024-11-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPayment', '0005_paymentmethod_card_brand_paymentmethod_card_last4'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
