# Generated by Django 5.0.3 on 2024-10-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='destination_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='place_of_origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
