# Generated by Django 4.2.16 on 2024-11-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTour', '0002_tour_destination_place_tour_place_of_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
