# Generated by Django 4.2.16 on 2024-11-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTour', '0003_reservation_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/tours/'),
        ),
    ]
