# Generated by Django 4.2.16 on 2024-11-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTour', '0004_tour_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='folio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='lodging_place',
            field=models.CharField(max_length=100),
        ),
    ]
