# Generated by Django 5.0.3 on 2024-10-14 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appTour', '0001_initial'),
        ('appUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_title', models.CharField(blank=True, max_length=200)),
                ('total_clients', models.IntegerField(default=0)),
                ('tour_description', models.TextField(blank=True, max_length=500)),
                ('earnings', models.FloatField(default=0)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appUser.agency')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='appTour.tour')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['agency'],
            },
        ),
    ]
