# Generated by Django 4.2.16 on 2024-11-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
