# Generated by Django 4.2.16 on 2024-11-15 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0017_alter_agency_profile_image_and_more'),
        ('appTour', '0004_tour_tour_image'),
        ('appDashboard', '0002_alter_reports_earnings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appUser.client')),
                ('tours', models.ManyToManyField(to='appTour.tour')),
            ],
            options={
                'verbose_name': 'Lista de Favoritos',
                'verbose_name_plural': 'Listas de Favoritos',
                'ordering': ['client'],
            },
        ),
    ]
