# Generated by Django 4.2 on 2024-11-16 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appTour', '0004_tour_tour_image'),
        ('appUser', '0017_alter_agency_profile_image_and_more'),
        ('appDashboard', '0003_favoritelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appUser.client')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTour.tour')),
            ],
            options={
                'verbose_name': 'Historial de Compra',
                'verbose_name_plural': 'Historiales de Compra',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
