# Generated by Django 4.2.16 on 2024-11-17 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDashboard', '0004_clientehistorial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClienteHistorial',
        ),
    ]
